### ISSUE TITLE
Add wrapper to container block

### ISSUE THREAD

**Issue by strarsis** [ArrayHQ/atomic-blocks#20]
For some themes it can be helpful to add a wrapper element, can an option added for this?

**Comment by mikemcalister** [comment]
Hi there, 

There is already a wrapper around the container block. There are actually a few containers wrapped around the innerblocks, such as `.ab-block-container` and `.ab-container-inside`.

**Comment by strarsis** [comment]
Would it be possible to add more, at least one, using some filter?

**Comment by mindctrl** [comment]
@strarsis can you describe what you're trying to do exactly so we can understand the use case?
