### ISSUE TITLE
Testimonial block: Removing person's title doesn't work as expected

### ISSUE THREAD

**Issue by mindctrl** [ArrayHQ/atomic-blocks#24]
This doesn't seem to happen every time, and I've been unable to reproduce reliably, but the gist of it is laid out below. I think it could be related to how weird it is to get back into the placeholder field/area once you've removed the title and poking around all the keys is causing something funky under the hood, but I could be way off base. Haven't dug into the code at all.

Removing the title results in the letter `F` or lowercase `f` being saved in the title.

Steps to reproduce:

- Add Testimonial block
- Add some text
- Add a name
- Add a title
- Save page
- Edit title and remove it
- Save page

Visually it looks like it was removed, but viewing it on the front end shows an `F` where the title goes. Editing the page again in the admin will reveal the `F`. If you try to remove it and save, you'll see it again appears to be removed but on the front end it's still there and if you refresh the admin edit page you'll see it reappear.

Atomic Blocks: 1.3.6
Gutenberg: 4.1.1
WP: 4.9.8

**Comment by mindctrl** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/1254870/48018422-ce2a6500-e0fe-11e8-8544-78e981b5c272.png)

**Comment by mikemcalister** [comment]
Fixed in 1.3.9.
