### ISSUE TITLE
Regenerate POT file

### ISSUE THREAD

**Issue by mindctrl** [ArrayHQ/atomic-blocks#26]
Once https://github.com/ArrayHQ/atomic-blocks/pull/25 is merged and right before we tag `1.3.7`, we need to regenerate the pot file so it includes all the strings.

**Comment by nathanrice** [comment]
I'm not sure what tool AB uses for POT generation, but I know that the WP.org tool doesn't scan JS files for translatable strings, and neither does the `grunt-wp-i18n` task. (AFAIK)

[This Babel plugin](https://github.com/WordPress/packages/blob/master/packages/babel-plugin-makepot/README.md) does, though.

**Comment by mikemcalister** [comment]
I thought CGB was doing POT but I guess not. There are some more clues [here](https://github.com/swissspidy/gutenberg-i18n-block).

**Comment by mikemcalister** [comment]
Ultimately used `wp i18n make-pot` in wp-cli to regenerate the strings in 1.3.7. More on that [here](https://github.com/swissspidy/gutenberg-i18n-block#usage).
