### ISSUE TITLE
Change default button colors

### ISSUE THREAD

**Issue by AndreaBarghigiani** [ArrayHQ/atomic-blocks#27]
Hi there,
I am working on a client project and looking forward for the 5.0 update I already installed Gutenberg and activated your awesome plugin.

I've declared few default colors but I do not see them when I use your blocks, especially the button ones.

There is a way that will let me override your default colours or I have to force the user to use the colour picker?

Thank you in advance,
Andrea

**Comment by mikemcalister** [comment]
Hi there, 

For now, you'll have to use the color picker. I'll take a closer look at whether it will be possible to override plugin color palettes in Gutenberg for a future release.
