### ISSUE TITLE
Load masonry and imagesloaded conditionally

### ISSUE THREAD

**Issue by pascalknecht** [ArrayHQ/atomic-blocks#30]
It would be great if masonry and imagesloaded javascript frontend files could only be loaded if needed.

**Comment by mikemcalister** [comment]
Hi there 

Masonry and imagesloaded isn't loading from the plugin, rather the theme. I've opened this issue on the [theme repo](https://github.com/ArrayHQ/atomic-blocks-theme/issues/29).

**Comment by pascalknecht** [comment]
I am not sure about that. I am not using your theme I am using my own
starter theme with no masonry depency.

Am Di., 4. Dez. 2018, 20:44 hat Mike McAlister <notifications@github.com>
geschrieben:

**Comment by mikemcalister** [comment]
Could be loading from another plugin then. We don't use masonry in the AB plugin anywhere.
