### ISSUE TITLE
[bug] Blocks not appear in gutenberg editor, console error InspectorControls

### ISSUE THREAD

**Issue by degie** [ArrayHQ/atomic-blocks#31]
When I activated plugin on clean install of Wordpress blocks not appear in Gutenberg editor and I can see error in devtools console from blocks.build.js?ver=1542790736:formatted:13012 
`Uncaught TypeError: Cannot read property 'InspectorControls' of undefined`

Gutenberg Version 4.5.1
Atomic Blocks Version 1.3.8 
Wordpress Version 4.9.8
nginx/1.4.6 (Ubuntu 14.04)
PHP 7.0.3

**Comment by mindctrl** [comment]
Two more reports on wordpress.org of this, and I also see the same.

https://wordpress.org/support/topic/activated-but-no-atomic-blocks/

https://wordpress.org/support/topic/blocks-not-working-with-gb-4-5-1/

**Comment by mikemcalister** [comment]
Hi there, 

Thanks for the report. This has been fixed in version 1.4.0. Give it a spin and let us know if you see anything else!

**Comment by degie** [comment]
> Hi there,
> 
> Thanks for the report. This has been fixed in version 1.4.0. Give it a spin and let us know if you see anything else!

Thanks @mikemcalister for fast fix, great job! It's working now like a charm!
