### ISSUE TITLE
Profile block error due to spacing

### ISSUE THREAD

**Issue by billerickson** [ArrayHQ/atomic-blocks#4]
After creating a page using the profile block, going back to edit it I get this error:

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/1D1G1Q0a372B1E0l1l46/Screen%20Shot%202018-04-25%20at%201.44.23%20PM.png?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=78851715)

It doesn't affect every block on the page, but if I save the page and the re-edit, more profile blocks get the same error.

The console displays an error message containing the actual and expected output. Here's a diff of the two outputs: https://www.diffchecker.com/0wygDzGZ

It appears the issue relates to white space being added to the content by WP.

If I click "Edit as HTML" I get an unknown error ([screenshot](https://cl.ly/042R3E1t2m3T)). If I click "Convert to Blocks" it changes the content to image and text blocks.

**Comment by mikemcalister** [comment]
Hey @billerickson, thanks for the report. I wasn't entirely able to reproduce your issue, but I saw a few improvements that may help. I just pushed up v1.1.1 to Github. You want to see if that does the trick and shoot me any results? 

Ultimately, I think transition this block to a nested block could help with the consistency of the output.

**Comment by billerickson** [comment]
Thanks!

After updating, all blocks were inaccessible ([screenshot](https://cl.ly/3I1C2C0B3T15)), but after rebuilding them everything seems to be working great.  I'll let you know if the issue pops up again.

Will future updates require the blocks to be rebuilt again? I didn't see the deprecated blocks API being used in that block, but I might have missed it. 

Also, would it be possible to not hardcode styles on the block by default? It would be necessary if they used the color pickers to set background and text colors, but when the block is initially created it would be nice if there weren't inline styles so a theme can provide default styling.  

I'm using this to override them in my theme:

```css
.ab-block-profile {
	padding: 0;
	background: transparent !important;
	color: $brown_1 !important;
}
```

**Comment by mikemcalister** [comment]
Dang, I had a feeling that might break the block. I hate how it handles those errors so harshly. With that fix in particular, there wasn't really a way to depreciate it to prevent that, at least that I know of. Going forward, you won't have to rebuild them.

As far as the styles, I'm not sure if that's possible or not. Right now, I'm following how the core blocks are handling styles. I haven't seen anything pop up that only applies the styles once the pickers are interacted with. I would surely be open to that though.
