### ISSUE TITLE
1.4.22: CTA block no longer takes alignment on front end

### ISSUE THREAD

**Issue by nickcernis** [ArrayHQ/atomic-blocks#45]
The `align…` class is missing from the CTA block on the front end after 1.4.22:

<img width="970" alt="edit_page_ _dev_ _wordpress" src="https://user-images.githubusercontent.com/647669/50903455-28f17d00-141e-11e9-93cc-4d8c32ecb65f.png">

Cause seems to be the align class missing from this commit: https://github.com/ArrayHQ/atomic-blocks/commit/4478d0307d1feaf354c006900b4a2cd19b36f630#diff-13e4e64d7ae491ce874522cd5abb55e4L32

<img width="1282" alt="dev_ _just_another_wordpress_site" src="https://user-images.githubusercontent.com/647669/50903515-50e0e080-141e-11e9-8564-b2e264e83716.png">

**Comment by mikemcalister** [comment]
The align class was removed from the block here because Gutenberg now outputs this class automatically on the block. What kind of issues is this creating for you folks on the theme side?

**Comment by mikemcalister** [comment]
It looks like the class is automatically output in the editor, but not on the front end. Makes sense. I will add this back in a quick update soon!

**Comment by nickcernis** [comment]
Confirmed fixed by https://github.com/ArrayHQ/atomic-blocks/pull/47.

<img width="1305" alt="cta_block_test" src="https://user-images.githubusercontent.com/647669/51274975-e5c07c80-19d0-11e9-9a5d-8ce8be14c6f4.png">

(I also tested alignwide.)
