### ISSUE TITLE
Remove custom color palettes in favor of theme color palette

### ISSUE THREAD

**Issue by mikemcalister** [ArrayHQ/atomic-blocks#52]
Some blocks have color palettes defined in the plugin, which prevents themes from overriding these color palettes. We can safely remove these and have the themes handle the colors.

**Comment by robincornett** [comment]
Can this issue be revisited, please? I was glad to see that the change was made, but when I use a theme color in an AB block, the hex code is still added as an inline style, whereas I expected the color slug to be used instead.

**Comment by mikemcalister** [comment]
Hi Robin, 

Which block in particular? There are some that use the core method and some that haven't been updated yet. They don't make it easy to use the core method, which is why some haven't been updated.

**Comment by robincornett** [comment]
Hi Mike, the ones I encountered were the container and CTA block--the background colors and the button colors used my theme defined colors in the editor, which was different from what I'd experienced before, but the output uses the hex codes. I set a background color on the container, using a theme defined color, and then a different theme color on the CTA button.
