### ISSUE TITLE
Fatal error on PHP versions prior to 5.4

### ISSUE THREAD

**Issue by mindctrl** [ArrayHQ/atomic-blocks#9]
Due to the array short syntax here: https://github.com/ArrayHQ/atomic-blocks/blob/c9a917ad9fda3a87b393c460db92146a977b5d6b/dist/init.php#L102

We should put some kind of PHP version check in here to avoid it, or convert it to `array()`. I prefer the former because we'll invariably let something like this slip in again since we're using modern PHP in dev, and writing old PHP sucks.

**Comment by mikemcalister** [comment]
Fixed in 1.2.2.
